function init_trHandheld()
{
	setup.trClothes.handheld = [
		{
			index: 0,
			name: "naked",
			name_ko: "벗음",
			variable: "naked",
			post: 0,
			description: "naked",
		},
		{
			index: 1,
			name: "umbrella",
			name_ko: "우산",
			variable: "umbrella",
			post: 0,
			description: "비를 막아준다.",
		},
		{
			index: 2,
			name: "parasol",
			name_ko: "파라솔",
			variable: "parasol",
			post: 2,
			description: "비를 막아준다.",
		},
		{
			index: 3,
			name: "sweet lolita parasol",
			name_ko: "스위트 로리타 파라솔",
			variable: "parasolsweet",
			post: 2,
			description: "비를 막아준다.",
		},
		{
			index: 4,
			name: "paper parasol",
			name_ko: "종이 파라솔",
			variable: "parasolpaper",
			post: 2,
			description: "비를 막기 위해, 투명 코팅이 되어 있다.",
		},
		{
			index: 5,
			name: "purse",
			name_ko: "핸드백",
			variable: "purse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},
		{
			index: 6,
			name: "heart purse",
			name_ko: "하트 모양 핸드백",
			variable: "heartpurse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},
		{
			index: 7,
			name: "messenger bag",
			name_ko: "메신저백",
			variable: "messengerbag",
			post: 0,
			description: "교과서를 들고 다닐 때 유용하다.",
		},
		{
			index: 8,
			name: "backpack",
			name_ko: "책가방",
			variable: "backpack",
			post: 0,
			description: "교과서를 들고 다닐 때 유용하다.",
		},
		{
			index: 9,
			name: "paper fan",
			name_ko: "종이 부채",
			variable: "paperfan",
			post: 1,
			description: "당신을 시원하게 해준다.",
		},
		{
			index: 10,
			name: "milkshake",
			name_ko: "밀크셰이크",
			variable: "milkshake",
			post: 1,
			description: "맛있고 상쾌해진다.",
		},
		{
			index: 11,
			name: "cigarette",
			name_ko: "담배",
			variable: "cigarette",
			post: 1,
			description: "나쁜 습관은 그리 멋지게 보이지 않는다.",
		},
		{
			index: 12,
			name: "feather duster",
			name_ko: "깃털 먼지털이개",
			variable: "featherduster",
			post: 1,
			description: "청소할 때 귀여워 보인다.",
		},
		{
			index: 13,
			name: "pom poms",
			name_ko: "폼폼",
			variable: "pompoms",
			post: 0,
			description: "당신 팀의 승리를 응원하기 위한 것.",
		},
		{
			index: 14,
			name: "balloon",
			name_ko: "풍선",
			variable: "balloon",
			post: 0,
			description: "손에서 놓지 말자.",
		},
		{
			index: 15,
			name: "heart balloon",
			name_ko: "하트모양 풍선",
			variable: "balloonheart",
			post: 0,
			description: "손에서 놓지 말자.",
		},
		{
			index: 16,
			name: "bag of popcorn",
			name_ko: "팝콘 봉지",
			variable: "popcorn",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 17,
			name: "gingerbread man",
			name_ko: "사람 모양 생강 쿠키",
			variable: "gingerbread",
			post: 1,
			description: "아주 맛있다. 여러 장면의 소품이다.",
		},
		{
			index: 18,
			name: "cup of lemonade",
			name_ko: "레모네이드 컵",
			variable: "lemonade",
			post: 0,
			description: "아주 맛있다.",
		},
		{
			index: 19,
			name: "hot drink",
			name_ko: "뜨거운 음료",
			variable: "cocoa",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 20,
			name: "mug",
			name_ko: "머그잔",
			variable: "mug",
			post: 0,
			description: "비어 있다.",
		},	
		{
			index: 21,
			name: "beer bottle",
			name_ko: "맥주병",
			variable: "beerbottle",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 22,
			name: "mug of beer",
			name_ko: "맥주잔",
			variable: "beermug",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 23,
			name: "shot glass",
			name_ko: "양주잔",
			variable: "shotglass",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 24,
			name: "wine glass",
			name_ko: "와인잔",
			variable: "wine",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 25,
			name: "torch",
			name_ko: "횃불",
			variable: "torch",
			post: 2,
			description: "불타올라라, 베이비, 불타올라라.",
		},	
		{
			index: 26,
			name: "gym bag",
			name_ko: "체육복 가방",
			variable: "gymbag",
			post: 0,
			description: "교과서를 들고 다닐 때 유용하다, 교과서에서 체육복 양말 냄새가 나는 것을 신경쓰지 않는다면.",
		},	
		{
			index: 27,
			name: "cup of tea",
			name_ko: "홍차컵",
			variable: "tea",
			post: 0,
			description: "뜨겁다, 왜냐하면 아이스 티는 교양없는 자들이나 마시는 것이기 때문에.",
		},	
		{
			index: 28,
			name: "cup of coffee",
			name_ko: "커피컵",
			variable: "coffee",
			post: 0,
			description: "뜨겁다.",
		},	
		{
			index: 29,
			name: "forkful of salad",
			name_ko: "포크로 찍어놓은 샐러드",
			variable: "salad",
			post: 1,
			description: "토끼 밥이다.",
		},	
		{
			index: 30,
			name: "forkful of pancake",
			name_ko: "포크로 찍어놓은 팬케이크",
			variable: "pancake",
			post: 1,
			description: "시럽이 듬뿍 발라져 있다.",
		},	
		{
			index: 31,
			name: "forkful of pasta",
			name_ko: "포크로 찍어놓은 파스타",
			variable: "pasta",
			post: 1,
			description: "엄마가 집에 와서 스파게티를 만들어 줬을 때 필요하다. 당신에게 엄마가 있다면.",
		},	
		{
			index: 32,
			name: "fork",
			name_ko: "포크",
			variable: "fork",
			post: 1,
			description: "식기다.",
		},	
		{
			index: 33,
			name: "spoon",
			name_ko: "숟가락",
			variable: "spoon",
			post: 0,
			description: "식기다.",
		},	
		{
			index: 34,
			name: "cream bun",
			name_ko: "크림빵",
			variable: "cream bun",
			post: 0,
			description: "음란한 액체로 더럽혀지지 않았다. 아마도.",
		},	
		{
			index: 35,
			name: "ornate telescope",
			name_ko: "화려하게 장식된 망원경",
			variable: "ornatetelescope",
			post: 0,
			description: "놀랍게도 멋진 모습이다.",
		},	
		{
			index: 36,
			name: "hand of cards",
			name_ko: "카드 손패",
			variable: "cards",
			post: 1,
			description: "운이 좋을 것 같아요?",
		},
		{
			index: 37,
			name: "cane",
			name_ko: "지팡이",
			variable: "cane",
			post: 1,
			description: "가볍고 위엄있어 보인다.",
		},
		{
			index: 38,
			name: "forearm crutch",
			name_ko: "목발",
			variable: "crutch",
			post: 2,
			description: "보조도구가 보통 그래야 하듯이, 비싸지 않다.",
		},
		{
			index: 39,
			name: "bottle of sunscreen",
			name_ko: "선크림 통",
			variable: "sunscreen",
			post: 0,
			description: "하얗고 끈적거린다.",
		},
		{
			index: 40,
			name: "scrap of fabric",
			name_ko: "옷 조각",
			variable: "rag",
			post: 0,
			description: "당신의 옷 조각은 조각조각 찢어졌다!",
		},
		{
			index: 41,
			name: "pill bottle",
			name_ko: "약 통",
			variable: "pill bottle",
			post: 1,
			description: "약을 먹는 것을 잊지 말자.",
		},
		{
			index: 42,
			name: "paintbrush",
			name_ko: "그림붓",
			variable: "paintbrush",
			post: 0,
			description: "예술가적 성향이 있는 사람들을 위해.",
		},
		{
			index: 43,
			name: "notebook",
			name_ko: "공책",
			variable: "notebook",
			post: 0,
			description: "기생충들에 대한 자세한 사항을 적어두기 위해.",
		},
		{
			index: 44,
			name: "net",
			name_ko: "그물",
			variable: "net",
			post: 2,
			description: "전부 다 잡고 말거야.",
		},
		{
			index: 45,
			name: "bottle of lube",
			name_ko: "윤활액 통",
			variable: "lube",
			post: 0,
			description: "젖으면 미끌미끌해진다.",
		},
		{
			index: 46,
			name: "breast pump",
			name_ko: "착유기",
			variable: "breast pump",
			post: 1,
			description: "당신의 집에서 편하게 신선한 우유를 생산한다.",
		},
		{
			index: 47,
			name: "can of hairspray",
			name_ko: "헤어 스프레이 캔",
			variable: "hairspray",
			post: 0,
			description: "꺼져라, 지독하게 헝클어진 머리카락이여, 내게서 꺼져라!",
		},
		{
			index: 48,
			name: "bottle of hair gel",
			name_ko: "헤어 젤 통",
			variable: "hairgel",
			post: 0,
			description: "꺼져라, 지독하게 헝클어진 머리카락이여, 내게서 꺼져라!",
		},
		{
			index: 49,
			name: "bottle of hair dye",
			name_ko: "염색약 통",
			variable: "hairdye",
			post: 0,
			description: "눈썹과 음모 전용.",
		},
		{
			index: 50,
			name: "dummy",
			name_ko: "공갈젖꼭지",
			variable: "dummy",
			post: 1,
			description: "아기용. 혹은 파티광용.",
		},
		{
			index: 51,
			name: "baby rattle",
			name_ko: "아기 딸랑이",
			variable: "toyrattle",
			post: 1,
			description: "엄마가 준 걸 흔들어 봐.",
		},
		{
			index: 52,
			name: "toy car",
			name_ko: "장난감 자동차",
			variable: "toycar",
			post: 1,
			description: "브렐카가 뉴웅 하고 가네.",
		},
		{
			index: 53,
			name: "stuffed bear",
			name_ko: "봉제인형",
			variable: "toybear",
			post: 0,
			description: "부드럽고 껴안기 좋다",
		},
		{
			index: 54,
			name: "tray",
			name_ko: "쟁반",
			variable: "tray",
			post: 0,
			description: "절대 떨어뜨리지 마라.",
		},
		{
			index: 55,
			name: "trash bag",
			name_ko: "쓰레기 봉지",
			variable: "trash bag",
			post: 1,
			description: "그야말로 쓰레기.",
		},
		{
			index: 56,
			name: "can of spray paint",
			name_ko: "스프레이 페인트 캔",
			variable: "spray paint",
			post: 0,
			description: "비행 청소년들의 최애 도구.",
		},
		{
			index: 57,
			name: "bar of soap",
			name_ko: "비누",
			variable: "soap",
			post: 1,
			description: "둥둥둥.",
		},
		{
			index: 58,
			name: "science textbook",
			name_ko: "과학 교과서",
			variable: "bookscience",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 59,
			name: "maths textbook",
			name_ko: "수학 교과서",
			variable: "bookmaths",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 60,
			name: "english textbook",
			name_ko: "영어 교과서",
			variable: "bookenglish",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 61,
			name: "history textbook",
			name_ko: "역사 교과서",
			variable: "bookhistory",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 62,
			name: "scarlet book",
			name_ko: "진홍색 책",
			variable: "bookscarlet",
			post: 0,
			description: "고전적인 영어 연극이다.",
		},
		{
			index: 63,
			name: "olive book",
			name_ko: "올리브색 책",
			variable: "bookolive",
			post: 0,
			description: "고전적인 크리스마스 이야기다.",
		},
		{
			index: 64,
			name: "science textbook",
			name_ko: "과학 교과서",
			variable: "bookscienceclosed",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 65,
			name: "maths textbook",
			name_ko: "수학 교과서",
			variable: "bookmathsclosed",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 66,
			name: "english textbook",
			name_ko: "영어 교과서",
			variable: "bookenglishclosed",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 67,
			name: "history textbook",
			name_ko: "역사 교과서",
			variable: "bookhistoryclosed",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 68,
			name: "scarlet book",
			name_ko: "진홍색 책",
			variable: "bookscarletclosed",
			post: 0,
			description: "고전적인 영어 연극이다.",
		},
		{
			index: 69,
			name: "olive book",
			name_ko: "올리브색 책",
			variable: "bookoliveclosed",
			post: 0,
			description: "고전적인 크리스마스 이야기다.",
		},
		{
			index: 70,
			name: "blood lemon",
			name_ko: "블러드 레몬",
			variable: "blood lemon",
			post: 0,
			description: "레몬 훔치는 매춘부들에 의해 수확되었다.",
		},
		{
			index: 71,
			name: "lemon",
			name_ko: "레몬",
			variable: "lemon",
			post: 0,
			description: "레몬 훔치는 매춘부들에 의해 수확되었다.",
		},
		{
			index: 72,
			name: "apple",
			name_ko: "사과",
			variable: "apple",
			post: 1,
			description: "의사 하퍼를 멀리하도록 해 주지는 않는다.",
		},
		{
			index: 73,
			name: "banana",
			name_ko: "바나나",
			variable: "banana",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 74,
			name: "blackberry",
			name_ko: "블랙베리",
			variable: "blackberry",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 75,
			name: "orange",
			name_ko: "오렌지",
			variable: "orange",
			post: 1,
			description: "괴혈병 예방에 도움이 된다.",
		},
		{
			index: 76,
			name: "peach",
			name_ko: "복숭아",
			variable: "peach",
			post: 1,
			description: "악어 혓바닥을 조심하라.",
		},
		{
			index: 77,
			name: "pear",
			name_ko: "배",
			variable: "pear",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 78,
			name: "honeycomb",
			name_ko: "벌집",	/* 꿀? */
			variable: "honeycomb",
			post: 0,
			description: "끈적거리고 아주 맛있다.",
		},
		{
			index: 79,
			name: "strawberry",
			name_ko: "딸기",
			variable: "strawberry",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 80,
			name: "plum",
			name_ko: "자두",
			variable: "plum",
			post: 1,
			description: "즙이 많고 달콤하다.",
		},
		{
			index: 81,
			name: "bag of breast milk",
			name_ko: "모유 가방",
			variable: "breast milk bag",
			post: 0,
			description: "바로 짠, 신선한 우유다.",
		},
		{
			index: 82,
			name: "bottle of breast milk",
			name_ko: "모유 병",
			variable: "breast milk bottle",
			post: 0,
			description: "바로 짠, 신선한 모유다.",
		},
		{
			index: 83,
			name: "bottle of semen",
			name_ko: "정액 병",
			variable: "semen bottle",
			post: 0,
			description: "바로 짠, 신선한 '우유'다.",
		},
		{
			index: 84,
			name: "bottle of milk",
			name_ko: "우유 병",
			variable: "milk bottle",
			post: 0,
			description: "바로 짠, 신선한 우유다.",
		},
		{
			index: 85,
			name: "baby bottle",
			name_ko: "젖병",
			variable: "baby bottle",
			post: 0,
			description: "먹여주는 게 가장 좋다.",
		},
		{
			index: 86,
			name: "mushroom",
			name_ko: "버섯",
			variable: "mushroom",
			post: 0,
			description: "재미있는 사람이다.",
		},
		{
			index: 87,
			name: "wolfshroom",
			name_ko: "늑대버섯",
			variable: "wolfshroom",
			post: 0,
			description: "늑대들이 허겁지겁 먹는다.",
		},
		{
			index: 88,
			name: "ghostshroom",
			name_ko: "유령버섯",
			variable: "ghostshroom",
			post: 0,
			description: "우리 주변의 균류이다.",
		},
		{
			index: 89,
			name: "pink mushroom",
			name_ko: "분홍색 버섯",
			variable: "pinkshroom",
			post: 0,
			description: "자연산 미약이다.",
		},
		{
			index: 90,
			name: "jar of pink fluid",
			name_ko: "분홍색 액체가 든 병",
			variable: "aphrodisiac jar",
			post: 0,
			description: "구현된 성욕.",
		},
		{
			index: 91,
			name: "condom",
			name_ko: "콘돔",
			variable: "condom",
			post: 0,
			description: "즙을 짜내기 전에 감싸두자.",
		},
		{
			index: 92,
			name: "black box",
			name_ko: "검은 상자",
			variable: "black box",
			post: 1,
			description: "랜드리가 부탁한 특별한 물건.",
		},
		{
			index: 93,
			name: "bird egg",
			name_ko: "새 알",
			variable: "bird egg",
			post: 2,
			description: "이 괴로운 시기에 당신에게 멋진 알을 드려도 될까요?",
		},
		{
			index: 94,
			name: "chocolate bar",
			name_ko: "초콜릿 바",
			variable: "chocolate bar",
			post: 1,
			description: "금색 티켓을 들어있지 않다.",
		},
		{
			index: 95,
			name: "bucket of candy",
			name_ko: "사탕 바구니",
			variable: "halloween",
			post: 1,
			description: "트릭-오어-트릿.",
		},
		{
			index: 96,
			name: "sucker",
			name_ko: "막대사탕",
			variable: "sucker",
			post: 0,
			description: "당신이 원하는 대로 핥아라.",
		},
		{
			index: 97,
			name: "cup of hot cocoa",
			name_ko: "핫초코 컵",
			variable: "hot cocoa",
			post: 0,
			description: "맛있다.",
		},
		{
			index: 98,
			name: "cup of hot cider",
			name_ko: "따뜻한 사과주 컵",
			variable: "hot cider",
			post: 0,
			description: "맛있다.",
		},
		{
			index: 99,
			name: "bronze key",
			name_ko: "청동 열쇠",
			variable: "bronze key",
			post: 1,
			description: "어떤 문들은 열리지 않은 채로 두는 게 낫다.",
		},
		{
			index: 100,
			name: "razor",
			name_ko: "면도기",
			variable: "razor",
			post: 1,
			description: "베이지 않도록 조심하라.",
		},
		{
			index: 101,
			name: "solo cup",
			name_ko: "일회용 컵",
			variable: "solo cup",
			post: 0,
			description: "파티 필수품이다.",
		},
		{
			index: 102,
			name: "salve jar",
			name_ko: "연고 병",
			variable: "salve",
			post: 0,
			description: "마사지 할 때 쓰면 좋다.",
		},
		{
			index: 103,
			name: "whisk",
			name_ko: "거품기",
			variable: "whisk",
			post: 1,
			description: "세계구급 크림빵을 만들기 위해.",
		},
		{
			index: 104,
			name: "candy box",
			name_ko: "사탕 상자",
			variable: "candy box",
			post: 1,
			description: "지나치게 달콤하다.",
		},
		{
			index: 105,
			name: "watering can",
			name_ko: "물뿌리개",
			variable: "watering can",
			post: 1,
			description: "마셔라, 이 목마른 개새끼들아.",
		},
		{
			index: 106,
			name: "broomstick",
			name_ko: "빗자루",
			variable: "witch broom",
			post: 1,
			description: "당신이 중력에 저항하게 해 주지는 않는다.",
		},
		{
			index: 107,
			name: "antique arrow",
			name_ko: "골동품 화살",
			variable: "arrow",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 108,
			name: "antique artillery shell",
			name_ko: "골동품 포탄",
			variable: "artillery",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 109,
			name: "antique bell",
			name_ko: "골동품 종",
			variable: "bell",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 110,
			name: "antique brass statuette",
			name_ko: "골동품 황동상",
			variable: "brass statuette",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 111,
			name: "antique bullet",
			name_ko: "골동품 총알",
			variable: "bullet",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 112,
			name: "antique candlestick",
			name_ko: "골동품 양초",
			variable: "candlestick",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 113,
			name: "antique cane",
			name_ko: "골동품 지팡이",
			variable: "sword cane",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 114,
			name: "antique chastity belt",
			name_ko: "골동품 정조대",
			variable: "chastity",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 115,
			name: "antique chocolate bar",
			name_ko: "골동품 초콜릿 바",
			variable: "chocolate",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 116,
			name: "antique copper coin",
			name_ko: "골동품 구리 동전",
			variable: "copper coin",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 117,
			name: "antique copper compass",
			name_ko: "골동품 구리 나침반",
			variable: "copper compass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 118,
			name: "antique copper ring",
			name_ko: "골동품 구리 반지",
			variable: "copper ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 119,
			name: "antique coral ring",
			name_ko: "골동품 산호 반지",
			variable: "coral ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 120,
			name: "antique crystal",
			name_ko: "골동품 수정",
			variable: "crystal",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 121,
			name: "antique pink crystal",
			name_ko: "골동품 분홍색 수정",
			variable: "crystal pink",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 122,
			name: "antique cup",
			name_ko: "골동품 컵",
			variable: "cup",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 123,
			name: "antique cutlass",
			name_ko: "골동품 커틀라스 검",
			variable: "cutlass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 124,
			name: "antique dagger",
			name_ko: "골동품 단검",
			variable: "dagger",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 125,
			name: "antique diamond",
			name_ko: "골동품 다이아몬드",
			variable: "diamond",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 126,
			name: "antique medical aid",
			name_ko: "골동품 의료용 기구",
			variable: "dildo",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 127,
			name: "antique disc",
			name_ko: "골동품 원반",
			variable: "disc",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 128,
			name: "antique figurine",
			name_ko: "골동품 조각상",
			variable: "figurine",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 129,
			name: "antique gem",
			name_ko: "골동품 보석",
			variable: "forest gem",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 130,
			name: "antique gold brooch",
			name_ko: "골동품 금 브로치",
			variable: "gold brooch",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 131,
			name: "antique gold coin",
			name_ko: "골동품 금 동전",
			variable: "gold coin",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 132,
			name: "antique grenade",
			name_ko: "골동품 수류탄",
			variable: "grenade",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 133,
			name: "antique horn",
			name_ko: "골동품 뿔",
			variable: "horn",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 134,
			name: "antique hourglass",
			name_ko: "골동품 모래시계",
			variable: "hourglass",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 135,
			name: "antique incense burner",
			name_ko: "골동품 향로",
			variable: "incense",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 136,
			name: "antique island arrow",
			name_ko: "골동품 섬사람 화살",
			variable: "islander arrow",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 137,
			name: "antique ivory box",
			name_ko: "골동품 상아 상자",
			variable: "ivory box",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 138,
			name: "antique ivory statuette",
			name_ko: "골동품 상아 조각품",
			variable: "ivory statuette",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 139,
			name: "antique map",
			name_ko: "골동품 지도",
			variable: "map",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 140,
			name: "antique mine sign",
			name_ko: "골동품 광산 간판",
			variable: "bailey",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 141,
			name: "antique rusted cutlass",
			name_ko: "골동품 녹슨 커틀라스 검",
			variable: "rusted cutlass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 142,
			name: "antique silver blade",
			name_ko: "골동품 은 칼날",
			variable: "silver blade",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 143,
			name: "antique silver brooch",
			name_ko: "골동품 은 브로치",
			variable: "silver brooch",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 144,
			name: "antique silver coin",
			name_ko: "골동품 은 동전",
			variable: "silver coin",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 145,
			name: "antique silver compass",
			name_ko: "골동품 은 나침반",
			variable: "silver compass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 146,
			name: "antique silver crown",
			name_ko: "골동품 은 왕관",
			variable: "silver crown",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 147,
			name: "antique silver dagger",
			name_ko: "골동품 은 단검",
			variable: "silver dagger",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 148,
			name: "antique silver goblet",
			name_ko: "골동품 은 잔",
			variable: "silver goblet",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 149,
			name: "antique silver mask",
			name_ko: "골동품 은 가면",
			variable: "silver mask",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 150,
			name: "antique silver ring",
			name_ko: "골동품 은 반지",
			variable: "silver ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 151,
			name: "antique tea caddy",
			name_ko: "골동품 찻잎 통",
			variable: "tea caddy",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 152,
			name: "antique trilobite",
			name_ko: "골동품 삼엽충",
			variable: "trilobite",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 153,
			name: "antique watch",
			name_ko: "골동품 시계",
			variable: "watch",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 154,
			name: "antique gold compass",
			name_ko: "골동품 금 나침반",
			variable: "gold compass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 155,
			name: "antique gold necklace",
			name_ko: "골동품 황금 목걸이",
			variable: "gold necklace",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 156,
			name: "antique gold ring",
			name_ko: "골동품 황금 반지",
			variable: "gold ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 157,
			name: "antique fetish",
			name_ko: "골동품 숭배물",
			variable: "fetish",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 158,
			name: "tube of parasite cream",
			name_ko: "기생충 기피 크림 튜브",
			variable: "parasite cream",
			post: 1,
			description: "기생충의 접근을 막는다.",
		},
		{
			index: 159,
			name: "truffle",
			name_ko: "송로버섯",
			variable: "truffle",
			post: 0,
			description: "퇴폐적이다.",
		},
		{
			index: 160,
			name: "antique islander mask",
			name_ko: "골동품 섬사람 가면",
			variable: "islander mask",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 161,
			name: "antique ivory necklace",
			name_ko: "골동품 상아 목걸이",
			variable: "ivory necklace",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 162,
			name: "antique stone talisman",
			name_ko: "골동품 돌 부적",
			variable: "stone talisman",
			post: 0,
			description: "박물관으로 가야 한다.",
		},

		{
			index: 163,
			name: "some lichen",
			name_ko: "이끼",
			variable: "lichen",
			post: 1,
			description: "과학을 위해.",
		},

		{
			index: 164,
			name: "leaf",
			name_ko: "나뭇잎",
			variable: "leaf",
			post: 0,
			description: "바스락거린다.",
		},

		{
			index: 165,
			name: "stuffed owl",
			name_ko: "봉제 부엉이",
			variable: "kylar owl",
			post: 1,
			description: "카메라? 그런 건 없다.",
		},

		{
			index: 166,
			name: "piece of junk",
			name_ko: "쓰레기",
			variable: "junk",
			post: 1,
			description: "쓸모없다.",
		},

		{
			index: 167,
			name: "hoe",
			name_ko: "괭이",
			variable: "hoe",
			post: 1,
			description: "매춘부가 아니라 농기구다.",
		},

		{
			index: 168,
			name: "torch",
			name_ko: "횃불",
			variable: "heavy duty torch",
			post: 2,
			description: "어둠 속의 빛.",
		},

		{
			index: 169,
			name: "hammer",
			name_ko: "망치",
			variable: "hammer",
			post: 1,
			description: "때가 되었다.",
		},

		{
			index: 170,
			name: "toy robot",
			name_ko: "장난감 로봇",
			variable: "robot",
			post: 0,
			description: "레트로.",
		},

		{
			index: 171,
			name: "plate of burnt food",
			name_ko: "탄 음식 접시",
			variable: "burnt",
			post: 1,
			description: "먹을 수 없다.",
		},

		{
			index: 172,
			name: "plate of unrecognisable slop",
			name_ko: "정체불명의 오물 접시",
			variable: "slop",
			post: 1,
			description: "먹을 수 없다.",
		},

		{
			index: 173,
			name: "plush clown",
			name_ko: "광대 인형",
			variable: "clown toy",
			post: 0,
			description: "순수한 재미, 혹은 끔찍함.",
		},

		{
			index: 174,
			name: "baby doll",
			name_ko: "아기 인형",
			variable: "baby doll",
			post: 0,
			description: "아이를 위한 아이.",
		},

		{
			index: 175,
			name: "net",
			name_ko: "그물망",
			variable: "handheld net",
			post: 0,
			description: "전부 잡아라.",
		},

		{
			index: 176,
			name: "sponge",
			name_ko: "스펀지",
			variable: "sponge",
			post: 1,
			description: "먹는 것이 아니다.",
		},

		{
			index: 177,
			name: "gold bar",
			name_ko: "금괴",
			variable: "gold bar",
			post: 1,
			description: "'구멍'에 쑤셔 넣으라고 만들어진 것이 아니다.",
		},

		{
			index: 178,
			name: "furniture catalogue",
			name_ko: "가구 카탈로그",
			variable: "catalogue",
			post: 1,
			description: "현명하게 선택할 것.",
		},

		{
			index: 179,
			name: "makeshift fabric rope",
			name_ko: "급조된 천 로프",
			variable: "fabric rope",
			post: 1,
			description: "대담한 탈출을 위하여.",
		},

		{
			index: 180,
			name: "salmon wellington",
			name_ko: "연어 웰링턴",
			variable: "salmon wellington",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 181,
			name: "feather",
			name_ko: "깃털",
			variable: "feather",
			post: 2,
			description: "날개처럼 가볍고, 판처럼 딱딱하다.",
		},

		{
			index: 182,
			name: "eyeshadow palette",
			name_ko: "아이섀도 팔레트",
			variable: "eyeshadow",
			post: 1,
			description: "섹시하고 여성스럽다.",
		},

		{
			index: 183,
			name: "dog treat",
			name_ko: "개밥",
			variable: "dog treat",
			post: 0,
			description: "착한 강아지를 위해.",
		},

		{
			index: 184,
			name: "flapjack",
			name_ko: "플랩 잭",
			variable: "flapjack",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 185,
			name: "scone",
			name_ko: "스콘",
			variable: "scone",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 186,
			name: "bag of crisps",
			name_ko: "감자칩",
			variable: "crisps",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 187,
			name: "box",
			name_ko: "상자",
			variable: "box",
			post: 1,
			description: "뭐가 들었지?",
		},

		{
			index: 188,
			name: "coconut",
			name_ko: "코코넛",
			variable: "coconut",
			post: 0,
			description: "라임과 잘 어울린다.",
		},

		{
			index: 189,
			name: "donut",
			name_ko: "도넛",
			variable: "donut",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 190,
			name: "chainsaw",
			name_ko: "전기톱",
			variable: "chainsaw",
			post: 0,
			description: "무기 아님.",
		},

		{
			index: 191,
			name: "butt plug",
			name_ko: "애널 플러그",
			variable: "butt plug",
			post: 1,
			description: "엉덩이 순결을 지켜주지는 못한다.",
		},

		{
			index: 192,
			name: "bullet vibe",
			name_ko: "총알 모양 바이브",
			variable: "bullet vibe",
			post: 1,
			description: "웅웅거린다.",
		},

		{
			index: 193,
			name: "broom",
			name_ko: "빗자루",
			variable: "broom",
			post: 1,
			description: "비행용 아님.",
		},

		{
			index: 194,
			name: "bracelet",
			name_ko: "팔찌",
			variable: "bracelet",
			post: 1,
			description: "빛난다.",
		},

		{
			index: 195,
			name: "broccoli",
			name_ko: "브로콜리",
			variable: "broccoli",
			post: 1,
			description: "먹을 수 있는 나무.",
		},

		{
			index: 196,
			name: "binder",
			name_ko: "바인더",
			variable: "binder",
			post: 1,
			description: "물건 정리용.",
		},

		{
			index: 197,
			name: "tin of food",
			name_ko: "음식이 든 깡통",
			variable: "food tin",
			post: 0,
			description: "토스트에 잘 어울린다.",
		},

		{
			index: 198,
			name: "bag of nuts",
			name_ko: "견과류 봉지",
			variable: "nuts",
			post: 1,
			description: "야금야금 먹자.",
		},

		{
			index: 199,
			name: "cabbage",
			name_ko: "양배추",
			variable: "cabbage",
			post: 1,
			description: "굴러가는 머리.",
		},

		{
			index: 200,
			name: "anal beads",
			name_ko: "애널 비즈",
			variable: "anal beads",
			post: 1,
			description: "거인을 위한 로자리오.",
		},

		{
			index: 201,
			name: "dumbbell",
			name_ko: "덤벨",
			variable: "weight",
			post: 2,
			description: "튼튼한 몸을 위해.",
		},

		{
			index: 202,
			name: "wallet",
			name_ko: "지갑",
			variable: "wallet",
			post: 0,
			description: "돈 내놔.",
		},

		{
			index: 203,
			name: "used condom",
			name_ko: "사용한 콘돔",
			variable: "used condom",
			post: 0,
			description: "정자 쓰레기통.",
		},

		{
			index: 204,
			name: "toothbrush",
			name_ko: "칫솔",
			variable: "toothbrush",
			post: 2,
			description: "위생적이다.",
		},

		{
			index: 205,
			name: "toolbox",
			name_ko: "도구 상자",
			variable: "toolbox",
			post: 1,
			description: "유용하다.",
		},

		{
			index: 206,
			name: "ticket",
			name_ko: "표",
			variable: "ticket",
			post: 1,
			description: "잃어버리지 말 것.",
		},

		{
			index: 207,
			name: "slug",
			name_ko: "민달팽이",
			variable: "tenta slug",
			post: 1,
			description: "미끄럽다.",
		},

		{
			index: 208,
			name: "strange fruit",
			name_ko: "이상한 과일",
			variable: "tenta fruit",
			post: 2,
			description: "돼지고기 맛이 남.",
		},

		{
			index: 209,
			name: "tarp",
			name_ko: "방수포",
			variable: "tarp",
			post: 1,
			description: "워터프루프.",
		},

		{
			index: 210,
			name: "spear",
			name_ko: "창",
			variable: "spear",
			post: 0,
			description: "창을 들고 구제를 얻어라. 우리는 이곳에 서서 영원히 하나되리.",
		},

		{
			index: 211,
			name: "shark tooth",
			name_ko: "상어 이빨",
			variable: "shark tooth",
			post: 2,
			description: "귀중한 감옥의 화폐.",
		},

		{
			index: 212,
			name: "stroker",
			name_ko: "오나홀",
			variable: "stroker",
			post: 2,
			description: "진짜 구멍을 찾을 수 없을 때는, 가게에서 산 것도 괜찮다.",
		},

		{
			index: 213,
			name: "stick",
			name_ko: "지팡이",
			variable: "stick",
			post: 1,
			description: "찌르기 좋다.",
		},

		{
			index: 214,
			name: "piece of wood",
			name_ko: "나무 조각",
			variable: "wood",
			post: 0,
			description: "아침에 잘 보인다.",
		},

		{
			index: 215,
			name: "pair of shears",
			name_ko: "전지가위",
			variable: "shears",
			post: 1,
			description: "딸깍딸깍.",
		},

		{
			index: 216,
			name: "dildo",
			name_ko: "딜도",
			variable: "small dildo",
			post: 1,
			description: "대물 성애자는 만족하지 못한다.",
		},

		{
			index: 217,
			name: "silver bar",
			name_ko: "은괴",
			variable: "silver bar",
			post: 1,
			description: "땅에 얽매인 보물.",
		},

		{
			index: 218,
			name: "shovel",
			name_ko: "삽",
			variable: "shovel",
			post: 0,
			description: "굴삭 장비.",
		},

		{
			index: 219,
			name: "screwdriver",
			name_ko: "스크류 드라이버",
			variable: "screwdriver",
			post: 1,
			description: "나사를 풀 때 유용하다.",
		},

		{
			index: 220,
			name: "sandwich",
			name_ko: "샌드위치",
			variable: "sandwich",
			post: 1,
			description: "먹기에 안전할 수도, 아닐 수도.",
		},

		{
			index: 221,
			name: "ring",
			name_ko: "반지",
			variable: "ring",
			post: 1,
			description: "빛난다.",
		},

		{
			index: 222,
			name: "chemical bottle",
			name_ko: "화학 플라스크",
			variable: "science flask",
			post: 1,
			description: "옷을 녹이기로 유명.",
		},

		{
			index: 223,
			name: "rat",
			name_ko: "쥐",
			variable: "rat",
			post: 1,
			description: "음식으로 분류하고 싶지 않다.",
		},

		{
			index: 224,
			name: "carnation",
			name_ko: "카네이션",
			variable: "carnation",
			post: 0,
			description: "향기롭다.",
		},

		{
			index: 225,
			name: "pickaxe",
			name_ko: "곡괭이",
			variable: "pickaxe",
			post: 1,
			description: "광산에 있을 때를 위해.",
		},

		{
			index: 226,
			name: "phone",
			name_ko: "핸드폰",
			variable: "phone",
			post: 0,
			description: "고아를 위한 것이 아니다.",
		},

		{
			index: 227,
			name: "pepper spray",
			name_ko: "후추 스프레이",
			variable: "pepperspray",
			post: 1,
			description: "불법이다.",
		},

		{
			index: 228,
			name: "pencil",
			name_ko: "연필",
			variable: "pencil",
			post: 2,
			description: "보편적인 쓰기 도구.",
		},

		{
			index: 229,
			name: "pen",
			name_ko: "펜",
			variable: "pen",
			post: 0,
			description: "보편적인 쓰기 도구.",
		},

		{
			index: 230,
			name: "pasty",
			name_ko: "패스티",
			variable: "pasty",
			post: 1,
			description: "맛나다.",
		},

		{
			index: 231,
			name: "stack of paper",
			name_ko: "종이 더미",
			variable: "papers",
			post: 1,
			description: "잡무.",
		},

		{
			index: 232,
			name: "carrot",
			name_ko: "당근",
			variable: "carrot",
			post: 0,
			description: "요즘 어때요, 박사님?",
		},

		{
			index: 233,
			name: "necklace",
			name_ko: "목걸이",
			variable: "necklace",
			post: 1,
			description: "빛난다.",
		},

		{
			index: 234,
			name: "tube of mascara",
			name_ko: "마스카라 튜브",
			variable: "mascara",
			post: 1,
			description: "섹시하고 여성적이다.",
		},

		{
			index: 235,
			name: "marker",
			name_ko: "유성펜",
			variable: "marker",
			post: 0,
			description: "보편적인 쓰기 도구.",
		},

		{
			index: 236,
			name: "lurker leather",
			name_ko: "럴커 가죽",
			variable: "lurker leather",
			post: 0,
			description: "럴커의 부산물.",
		},

		{
			index: 237,
			name: "lurker",
			name_ko: "럴커",
			variable: "lurker",
			post: 1,
			description: "기묘한 울음소리를 내는 생명체.",
		},

		{
			index: 238,
			name: "lockpick",
			name_ko: "락픽",
			variable: "lockpick",
			post: 0,
			description: "진짜배기 도둑들의 필수품.",
		},

		{
			index: 239,
			name: "tube of lipstick",
			name_ko: "립스틱 튜브",
			variable: "lipstick",
			post: 1,
			description: "섹시하고 여성적이다.",
		},

		{
			index: 240,
			name: "dildo",
			name_ko: "딜도",
			variable: "dildo",
			post: 1,
			description: "진짜 좆을 찾을 수 없다면, 가게에서 산 것도 괜찮다.",
		},

		{
			index: 241,
			name: "pair of shears",
			name_ko: "정원용 가위",
			variable: "hedge shears",
			post: 1,
			description: "당신의 수풀을 깨끗하고 근사하게 유지한다.",
		},

		{
			index: 242,
			name: "wine bottle",
			name_ko: "와인병",
			variable: "wine bottle",
			post: 0,
			description: "술이다.",
		},

		{
			index: 243,
			name: "volleyball",
			name_ko: "배구공",
			variable: "volleyball",
			post: 0,
			description: "때리기 쉬운 공.",
		},

		{
			index: 244,
			name: "glowstick",
			name_ko: "반짝이 봉",
			variable: "glowstick",
			post: 0,
			description: "발광한다.",
		},

		{
			index: 245,
			name: "pinwheel",
			name_ko: "회전 폭죽",
			variable: "pinwheel",
			post: 0,
			description: "기발함으로 가득하다.",
		},

		{
			index: 246,
			name: "bucket",
			name_ko: "바구니",
			variable: "bucket",
			post: 1,
			description: "당신의 죄를 씻어낸다.",
		},

		{
			index: 247,
			name: "brush",
			name_ko: "브러시",
			variable: "brush",
			post: 1,
			description: "동물 털로 만들어졌다.",
		},

		{
			index: 248,
			name: "dog bowl",
			name_ko: "개밥그릇",
			variable: "dog bowl",
			post: 0,
			description: "독신자용 식사. 혹은 개밥.",
		},

		{
			index: 249,
			name: "dog leash",
			name_ko: "개 목줄",
			variable: "dog leash",
			post: 2,
			description: "이상성욕 플레이에는 적합하지 않다.",
		},

		{
			index: 250,
			name: "jar of jam",
			name_ko: "잼 병",
			variable: "jam",
			post: 0,
			description: "요리에 유용하다.",
		},

		{
			index: 251,
			name: "notebook",
			name_ko: "노트",
			variable: "notebook",
			post: 1,
			description: "자세한 기록을 위해.",
		},

		{
			index: 252,
			name: "basket of fish",
			name_ko: "생선 바구니",
			variable: "basket of fish",
			post: 1,
			description: "하피의 식사.",
		},

		{
			index: 253,
			name: "blusher",
			name_ko: "블러셔",
			variable: "blusher",
			post: 1,
			description: "섹시하고 여성스럽다.",
		},

		{
			index: 254,
			name: "brown bag",
			name_ko: "갈색 가방",
			variable: "brown bag",
			post: 0,
			description: "뭐가 들었지?",
		},

		{
			index: 255,
			name: "cheese-covered trout",
			name_ko: "치즈를 얹은 송어",
			variable: "cheese covered trout",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 256,
			name: "china dish",
			name_ko: "중국풍 접시",
			variable: "china",
			post: 1,
			description: "화려하다.",
		},

		{
			index: 257,
			name: "cigar",
			name_ko: "시가",
			variable: "cigar",
			post: 1,
			description: "멋지게 보여서는 안 되는 나쁜 습관.",
		},

		{
			index: 258,
			name: "piece of paper",
			name_ko: "종잇조각",
			variable: "paper",
			post: 0,
			description: "종잇조각. 쓸모없다.",
		},

		{
			index: 259,
			name: "first aid kit",
			name_ko: "구급상자",
			variable: "first aid",
			post: 1,
			description: "제네바 조약을 위반하지 않음.",
		},

		{
			index: 260,
			name: "tart",
			name_ko: "타르트",
			variable: "tart",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 261,
			name: "knife",
			name_ko: "나이프",
			variable: "knife",
			post: 1,
			description: "무기 아님.",
		},

		{
			index: 262,
			name: "ladle",
			name_ko: "국자",
			variable: "ladle",
			post: 1,
			description: "수프를 쏟지 않게 조심하라.",
		},

		{
			index: 263,
			name: "lunch tray",
			name_ko: "식판",
			variable: "lunch tray",
			post: 0,
			description: "식당 잔반용.",
		},

		{
			index: 264,
			name: "plate of steak",
			name_ko: "스테이크 접시",
			variable: "steak",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 265,
			name: "odd drink",
			name_ko: "이상한 음료",
			variable: "odd drink",
			post: 1,
			description: "유해한 부작용의 가능성이 있습니다.",
		},

		{
			index: 266,
			name: "pregnancy test",
			name_ko: "임신 테스트기",
			variable: "pregnancy test",
			post: 1,
			description: "좋거나 나쁜 소식.",
		},

		{
			index: 267,
			name: "bundle of laundry",
			name_ko: "빨랫감",
			variable: "laundry",
			post: 0,
			description: "오렌지 이즈 더 뉴 블랙.",
		},

		{
			index: 268,
			name: "rope",
			name_ko: "밧줄",
			variable: "rope",
			post: 2,
			description: "유용하다.",
		},

		{
			index: 269,
			name: "rope",
			name_ko: "밧줄",
			variable: "rope climb",
			post: 2,
			description: "유용하다.",
		},

		{
			index: 270,
			name: "snowball",
			name_ko: "눈 뭉치",
			variable: "snowball",
			post: 1,
			description: "자연의 무기.",
		},

		{
			index: 271,
			name: "soft drink can",
			name_ko: "탄산음료 캔",
			variable: "soft drink can",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 272,
			name: "bowl",
			name_ko: "수프 그릇",
			variable: "soup bowl",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 273,
			name: "packet of sweets",
			name_ko: "간식 봉지",
			variable: "packet of sweets",
			post: 1,
			description: "맛나다.",
		},

		{
			index: 274,
			name: "thermos",
			name_ko: "텀블러",
			variable: "thermos",
			post: 1,
			description: "휴대용 음료 용기.",
		},

		{
			index: 275,
			name: "flask",
			name_ko: "힙 플라스크",
			variable: "flask",
			post: 1,
			description: "휴대용 음료 용기.",
		},

		{
			index: 276,
			name: "wooden spoon",
			name_ko: "나무 수저",
			variable: "wooden spoon",
			post: 1,
			description: "보편적인 요리 도구.",
		},

		{
			index: 277,
			name: "daisy",
			name_ko: "데이지",
			variable: "daisy",
			post: 1,
			description: "향기롭다.",
		},

		{
			index: 278,
			name: "basket",
			name_ko: "바구니",
			variable: "basket",
			post: 1,
			description: "시장에 낼 상품을 모으기 위해.",
		},

		{
			index: 279,
			name: "garlic",
			name_ko: "마늘",
			variable: "garlic",
			post: 2,
			description: "악을 멀리한다.",
		},

		{
			index: 280,
			name: "lily",
			name_ko: "백합",
			variable: "lily",
			post: 0,
			description: "향기롭다.",
		},

		{
			index: 281,
			name: "lotus",
			name_ko: "연꽃",
			variable: "lotus",
			post: 0,
			description: "향기롭다.",
		},

		{
			index: 282,
			name: "onion",
			name_ko: "양파",
			variable: "onion",
			post: 1,
			description: "울음의 가능성 있음.",
		},

		{
			index: 283,
			name: "orchid",
			name_ko: "난초",
			variable: "orchid",
			post: 1,
			description: "향기롭다.",
		},

		{
			index: 284,
			name: "giant pearl",
			name_ko: "거대한 진주",
			variable: "oyster pearl",
			post: 1,
			description: "비싸다.",
		},

		{
			index: 285,
			name: "plumeria",
			name_ko: "플루메리아",
			variable: "plumeria",
			post: 1,
			description: "향기롭다.",
		},

		{
			index: 286,
			name: "potato",
			name_ko: "감자",
			variable: "potato",
			post: 1,
			description: "튼튼하고 쓸모가 많다.",
		},

		{
			index: 287,
			name: "rose",
			name_ko: "장미",
			variable: "rose",
			post: 1,
			description: "향기롭다.",
		},

		{
			index: 288,
			name: "strange flower",
			name_ko: "이상한 꽃",
			variable: "strange flower",
			post: 0,
			description: "향기롭다.",
		},

		{
			index: 289,
			name: "tulip",
			name_ko: "튤립",
			variable: "tulip",
			post: 0,
			description: "향기롭다.",
		},

		{
			index: 290,
			name: "turnip",
			name_ko: "순무",
			variable: "turnip",
			post: 1,
			description: "튼튼하고 쓸모가 많다.",
		},

		{
			index: 291,
			name: "bacon",
			name_ko: "베이컨",
			variable: "bacon",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 292,
			name: "bread",
			name_ko: "빵",
			variable: "bread",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 293,
			name: "stick of butter",
			name_ko: "버터 스틱",
			variable: "butter",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 294,
			name: "cookie",
			name_ko: "쿠키",
			variable: "cookie",
			post: 1,
			description: "맛나다.",
		},

		{
			index: 295,
			name: "head of cauliflower",
			name_ko: "콜리플라워",
			variable: "cauliflower",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 296,
			name: "cherry",
			name_ko: "체리",
			variable: "cherry",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 297,
			name: "raw meat",
			name_ko: "날고기",
			variable: "meat",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 298,
			name: "chilli pepper",
			name_ko: "고추",
			variable: "chilli pepper",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 299,
			name: "plate of clams",
			name_ko: "조개 한 접시",
			variable: "clams",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 300,
			name: "cocoa powder",
			name_ko: "코코아 파우더",
			variable: "cocoa powder",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 301,
			name: "biscuit",
			name_ko: "비스켓",
			variable: "biscuit",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 302,
			name: "cream",
			name_ko: "크림",
			variable: "cream",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 303,
			name: "date",
			name_ko: "대추",
			variable: "date",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 304,
			name: "bag of flour",
			name_ko: "밀가루 한 봉지",
			variable: "flour",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 305,
			name: "raw fish",
			name_ko: "날 생선",
			variable: "fish",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 306,
			name: "jar of honey",
			name_ko: "꿀 단지",
			variable: "honey",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 307,
			name: "lime",
			name_ko: "라임",
			variable: "lime",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 308,
			name: "oats",
			name_ko: "귀리",
			variable: "oats",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 309,
			name: "pastry dough",
			name_ko: "페이스트리 반죽",
			variable: "pastry dough",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 310,
			name: "pepper",
			name_ko: "피망",
			variable: "pepper",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 311,
			name: "prawns",
			name_ko: "새우",
			variable: "prawns",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 312,
			name: "salt",
			name_ko: "소금병",
			variable: "salt",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 313,
			name: "sausage",
			name_ko: "소세지",
			variable: "sausage",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 314,
			name: "spatula",
			name_ko: "주걱",
			variable: "spatula",
			post: 0,
			description: "보편적인 요리 도구.",
		},

		{
			index: 315,
			name: "spinach",
			name_ko: "시금치",
			variable: "spinach",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 316,
			name: "bag of sugar",
			name_ko: "설탕 봉지",
			variable: "sugar",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 317,
			name: "tomato",
			name_ko: "토마토",
			variable: "tomato",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 318,
			name: "bottle of vegetable oil",
			name_ko: "야채유 병",
			variable: "vegetable oil",
			post: 0,
			description: "요리에 쓰인다.",
		},

		{
			index: 319,
			name: "bowl of wheat",
			name_ko: "밀",
			variable: "wheat bowl",
			post: 2,
			description: "요리에 쓰인다.",
		},

		{
			index: 320,
			name: "bag of rice",
			name_ko: "쌀 봉지",
			variable: "rice",
			post: 1,
			description: "요리에 쓰인다.",
		},

		{
			index: 321,
			name: "apple crumble",
			name_ko: "애플 크럼블",
			variable: "apple crumble",
			post: 2,
			description: "수제 요리.",
		},

		{
			index: 322,
			name: "apple strudel",
			name_ko: "사과 슈트루델",
			variable: "apple strudel",
			post: 2,
			description: "수제 요리.",
		},

		{
			index: 323,
			name: "bowl of porridge",
			name_ko: "포리지 접시",
			variable: "porridge",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 324,
			name: "banana bread",
			name_ko: "바나나 빵",
			variable: "banana bread",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 325,
			name: "bangers and mash",
			name_ko: "소세지와 으깬 감자",
			variable: "bangers and mash",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 326,
			name: "beef wellington",
			name_ko: "비프 웰링턴",
			variable: "beef wellington",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 327,
			name: "brownie",
			name_ko: "브라우니",
			variable: "brownie",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 328,
			name: "slice of cake",
			name_ko: "케이크 한 조각",
			variable: "cake slice",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 329,
			name: "cheesy cauliflower",
			name_ko: "콜리플라워 치즈",
			variable: "cauliflower cheese",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 330,
			name: "cheese",
			name_ko: "치즈",
			variable: "cheese",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 331,
			name: "cheese and crackers",
			name_ko: "치즈 앤 크래커",
			variable: "cheese and crackers",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 332,
			name: "buns",
			name_ko: "번",
			variable: "buns",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 333,
			name: "bun",
			name_ko: "번",
			variable: "bun",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 334,
			name: "chicken tikka masala",
			name_ko: "치킨 티카 마살라",
			variable: "chicken tikka masala",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 335,
			name: "chicken vindaloo",
			name_ko: "치킨 반달루",
			variable: "chicken vindaloo",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 336,
			name: "chilli con carne",
			name_ko: "칠리 콘 카르네",
			variable: "chilli con carne",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 337,
			name: "chips",
			name_ko: "감자칩",
			variable: "chips",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 338,
			name: "plate of chocolate chip cookies",
			name_ko: "쿠키 한 접시",
			variable: "cookie plate",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 339,
			name: "samosas",
			name_ko: "사모사",
			variable: "samosas",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 340,
			name: "creme brulee",
			name_ko: "크렘브륄레",
			variable: "creme brulee",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 341,
			name: "plate of crumpets",
			name_ko: "크럼핏",
			variable: "crumpets",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 342,
			name: "plate of flapjacks",
			name_ko: "플랩 잭 한 접시",
			variable: "flapjacks",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 343,
			name: "full English breakfast",
			name_ko: "영국식 정통 아침식사",
			variable: "full english",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 344,
			name: "honeyed pork",
			name_ko: "꿀로 졸인 돼지고기",
			variable: "honeyed pork",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 345,
			name: "kedgeree",
			name_ko: "케저리",
			variable: "kedgeree",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 346,
			name: "lasagne",
			name_ko: "라자냐",
			variable: "lasagne",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 347,
			name: "slice of pie",
			name_ko: "파이 한 조각",
			variable: "pie slice",
			post: 0,
			description: "맛나다.",
		},

		{
			index: 348,
			name: "plate of pasta",
			name_ko: "파스타 한 접시",
			variable: "pasta plate",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 349,
			name: "bowl of macaroni and cheese",
			name_ko: "마카로니 앤 치즈 한 그릇",
			variable: "macaroni and cheese",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 350,
			name: "pie",
			name_ko: "파이",
			variable: "pie",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 351,
			name: "naan",
			name_ko: "난",
			variable: "naan",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 352,
			name: "omelette",
			name_ko: "오믈렛",
			variable: "omelette",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 353,
			name: "onion bhaji",
			name_ko: "양파 바지",
			variable: "onion bhaji",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 354,
			name: "peach panzanella",
			name_ko: "복숭아 팡젤넬라",
			variable: "peach panzanella",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 355,
			name: "pizza",
			name_ko: "피자",
			variable: "pizza",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 356,
			name: "pudding",
			name_ko: "푸딩",
			variable: "pudding",
			post: 0,
			description: "수제 요리.",
		},

		{
			index: 357,
			name: "slice of plum pudding",
			name_ko: "자두 푸딩 한 덩이",
			variable: "plum pudding",
			post: 1,
			description: "맛나다.",
		},

		{
			index: 358,
			name: "poached pear",
			name_ko: "데친 배",
			variable: "poached pear",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 359,
			name: "stack of potato pancakes",
			name_ko: "감자 팬케이크 접시",
			variable: "potato pancakes",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 360,
			name: "quiche",
			name_ko: "키슈",
			variable: "quiche",
			post: 1,
			description: "수제 요리.",
		},

		{
			index: 361,
			name: "heart hand warmer",
			name_ko: "하트 모양 손난로",
			variable: "heart hand warmer",
			post: 1,
			description: "당신의 손을 따끈따끈하게.",
		},

		{
			index: 362,
			name: "poppy",
			name_ko: "양귀비",
			variable: "poppy",
			post: 1,
			description: "향기롭다.",
		},

		{
			index: 363,
			name: "chew toy",
			name_ko: "씹는 장난감",
			variable: "chew toy",
			post: 0,
			description: "늑대의 치악력을 견디는 내구성.",
		},

		{
			index: 364,
			name: "signed cricket ball",
			name_ko: "사인된 크리켓 볼",
			variable: "signed cricket ball",
			post: 2,
			description: "삼주문의 고가품.",
		},

		{
			index: 365,
			name: "floral parasol",
			name_ko: "꽃무늬 파라솔",
			variable: "floralparasol",
			post: 2,
			description: "비를 막아준다.",
		},

		{
			index: 366,
			name: "regal parasol",
			name_ko: "장엄한 파라솔",
			variable: "regal parasol",
			post: 2,
			description: "비를 막아준다.",
		},

		{
			index: 367,
			name: "clock purse",
			name_ko: "시계 모양 핸드백",
			variable: "clock purse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},

		{
			index: 368,
			name: "cloud purse",
			name_ko: "구름 모양 핸드백",
			variable: "cloud purse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},

		{
			index: 369,
			name: "envelope",
			name_ko: "봉투",
			variable: "envelope",
			post: 1,
			description: "기밀이다.",
		},

		{
			index: 370,
			name: "plastic card",
			name_ko: "플라스틱 카드",
			variable: "keycard",
			post: 1,
			description: "귀중하다.",
		},

		{
			index: 371,
			name: "stolen purse",
			name_ko: "훔친 핸드백",
			variable: "stolen purse",
			post: 0,
			description: "돈 내놔.",
		},

		{
			index: 372,
			name: "cash",
			name_ko: "현금",
			variable: "cash",
			post: 0,
			description: "돈 내놔.",
		},

		{
			index: 373,
			name: "mop",
			name_ko: "대걸레",
			variable: "mop",
			post: 1,
			description: "갑판 청소용.",
		},

		{
			index: 374,
			name: "rolled poster",
			name_ko: "둘둘 말린 포스터",
			variable: "rolled poster",
			post: 1,
			description: "붙일 수 있는 포스터.",
		},

		{
			index: 375,
			name: "litter stick",
			name_ko: "쓰레기용 집게",
			variable: "litter stick",
			post: 1,
			description: "사회에 진 빚을 갚자.",
		},

		{
			index: 376,
			name: "rock",
			name_ko: "바위",
			variable: "rock",
			post: 1,
			description: "카메라가 숨겨져 있을지도",
		},

		{
			index: 377,
			name: "rubber",
			name_ko: "지우개",
			variable: "rubber",
			post: 1,
			description: "콘돔 아님.",
		},

		{
			index: 378,
			name: "scissors",
			name_ko: "가위",
			variable: "scissors",
			post: 1,
			description: "싹둑싹둑.",
		},

		{
			index: 379,
			name: "water bottle",
			name_ko: "물병",
			variable: "water bottle",
			post: 0,
			description: "수분보충을 도와준다.",
		},

		{
			index: 380,
			name: "snowglobe",
			name_ko: "스노우 글로브",
			variable: "snowglobe",
			post: 1,
			description: "스농스노우 글로브로브.",
		},

		{
			index: 381,
			name: "potted plant",
			name_ko: "화분",
			variable: "plant pot",
			post: 0,
			description: "창가에 두기 딱 좋다.",
		},

		{
			index: 382,
			name: "large teddy bear",
			name_ko: "큰 테디베어",
			variable: "large teddy bear",
			post: 1,
			description: "귀중하다.",
		},

		{
			index: 383,
			name: "plushie",
			name_ko: "봉제인형",
			variable: "plushie",
			post: 0,
			description: "폭신하고 안기 좋다.",
		},

		{
			index: 384,
			name: "pillow",
			name_ko: "베개",
			variable: "pillow",
			post: 1,
			description: "폭신하고 안기 좋다.",
		},

		{
			index: 385,
			name: "clipboard",
			name_ko: "클립보드",
			variable: "clipboard",
			post: 1,
			description: "공적으로 보인다.",
		},

		{
			index: 386,
			name: "and a pencil",
			name_ko: "그리고 연필",
			variable: "write",
			post: 2,
			description: "그렇게 적어 주세요.",
		},

		{
			index: 387,
			name: "teddy backpack",
			name_ko: "테디베어 백팩",
			variable: "teddy backpack",
			post: 0,
			description: "교과서를 넣기에 유용하다.",
		},

		{
			index: 388,
			name: "star purse",
			name_ko: "별 모양 핸드백",
			variable: "star purse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},

		{
			index: 389,
			name: "pamphlet",
			name_ko: "책자",
			variable: "pamphlet",
			post: 1,
			description: "프로파간다.",
		},

		{
			index: 390,
			name: "walkie talkie",
			name_ko: "무전기",
			variable: "walkie talkie",
			post: 1,
			description: "치지직, 오버.",
		},

		{
			index: 391,
			name: "riding crop",
			name_ko: "승마 채찍",
			variable: "crop",
			post: 0,
			description: "따끔거린다.",
		},

		{
			index: 392,
			name: "whip",
			name_ko: "채찍",
			variable: "whip",
			post: 0,
			description: "따끔거린다.",
		},

		{
			index: 393,
			name: "candy cane",
			name_ko: "사탕 지팡이",
			variable: "candy cane",
			post: 1,
			description: "먹는 것이 아니다. 핥으면 안 된다.",
		},

		{
			index: 394,
			name: "stone pendant",
			name_ko: "돌 펜던트",
			variable: "stone pendant",
			post: 1,
			description: "단순한 끈에 새겨진 낡고 성스러운 상징.",
		},

		{
			index: 395,
			name: "whale bone dagger",
			name_ko: "고래뼈 대검",
			variable: "whale bone dagger",
			post: 0,
			description: "가장 달콤한 골수로 조각되었다. 늑골 사이에 밀어넣는 것만으로도, 영혼을 풍요롭게 한다.",
		},

		{
			index: 396,
			name: "tote bag",
			name_ko: "토트 백",
			variable: "totebag",
			post: 0,
			description: "교과서를 들고 다니기 유용하다.",
		},
	];
}
window.init_trHandheld = init_trHandheld;

